/*
 * apaleo Identity API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identityclient

import (
	"encoding/json"
	"time"
)

// InvitationModel struct for InvitationModel
type InvitationModel struct {
	// Email address, used as the login
	Email string `json:"email"`
	// Properties that user has access to
	Properties *[]string `json:"properties,omitempty"`
	// If set to {true}, user has full access to all properties.
	IsAccountAdmin bool `json:"isAccountAdmin"`
	// Role this user is invited to. If more than one, returns the first.
	Role *string `json:"role,omitempty"`
	// Roles that user has access to
	Roles *[]string `json:"roles,omitempty"`
	// Email of the user making the invitation
	InvitedBy string `json:"invitedBy"`
	// Date the invitation was made
	Created time.Time `json:"created"`
}

// NewInvitationModel instantiates a new InvitationModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvitationModel(email string, isAccountAdmin bool, invitedBy string, created time.Time) *InvitationModel {
	this := InvitationModel{}
	this.Email = email
	this.IsAccountAdmin = isAccountAdmin
	this.InvitedBy = invitedBy
	this.Created = created
	return &this
}

// NewInvitationModelWithDefaults instantiates a new InvitationModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvitationModelWithDefaults() *InvitationModel {
	this := InvitationModel{}
	return &this
}

// GetEmail returns the Email field value
func (o *InvitationModel) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *InvitationModel) GetEmailOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *InvitationModel) SetEmail(v string) {
	o.Email = v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *InvitationModel) GetProperties() []string {
	if o == nil || o.Properties == nil {
		var ret []string
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvitationModel) GetPropertiesOk() (*[]string, bool) {
	if o == nil || o.Properties == nil {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *InvitationModel) HasProperties() bool {
	if o != nil && o.Properties != nil {
		return true
	}

	return false
}

// SetProperties gets a reference to the given []string and assigns it to the Properties field.
func (o *InvitationModel) SetProperties(v []string) {
	o.Properties = &v
}

// GetIsAccountAdmin returns the IsAccountAdmin field value
func (o *InvitationModel) GetIsAccountAdmin() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsAccountAdmin
}

// GetIsAccountAdminOk returns a tuple with the IsAccountAdmin field value
// and a boolean to check if the value has been set.
func (o *InvitationModel) GetIsAccountAdminOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.IsAccountAdmin, true
}

// SetIsAccountAdmin sets field value
func (o *InvitationModel) SetIsAccountAdmin(v bool) {
	o.IsAccountAdmin = v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *InvitationModel) GetRole() string {
	if o == nil || o.Role == nil {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvitationModel) GetRoleOk() (*string, bool) {
	if o == nil || o.Role == nil {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *InvitationModel) HasRole() bool {
	if o != nil && o.Role != nil {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *InvitationModel) SetRole(v string) {
	o.Role = &v
}

// GetRoles returns the Roles field value if set, zero value otherwise.
func (o *InvitationModel) GetRoles() []string {
	if o == nil || o.Roles == nil {
		var ret []string
		return ret
	}
	return *o.Roles
}

// GetRolesOk returns a tuple with the Roles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvitationModel) GetRolesOk() (*[]string, bool) {
	if o == nil || o.Roles == nil {
		return nil, false
	}
	return o.Roles, true
}

// HasRoles returns a boolean if a field has been set.
func (o *InvitationModel) HasRoles() bool {
	if o != nil && o.Roles != nil {
		return true
	}

	return false
}

// SetRoles gets a reference to the given []string and assigns it to the Roles field.
func (o *InvitationModel) SetRoles(v []string) {
	o.Roles = &v
}

// GetInvitedBy returns the InvitedBy field value
func (o *InvitationModel) GetInvitedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InvitedBy
}

// GetInvitedByOk returns a tuple with the InvitedBy field value
// and a boolean to check if the value has been set.
func (o *InvitationModel) GetInvitedByOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.InvitedBy, true
}

// SetInvitedBy sets field value
func (o *InvitationModel) SetInvitedBy(v string) {
	o.InvitedBy = v
}

// GetCreated returns the Created field value
func (o *InvitationModel) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *InvitationModel) GetCreatedOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *InvitationModel) SetCreated(v time.Time) {
	o.Created = v
}

func (o InvitationModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["email"] = o.Email
	}
	if o.Properties != nil {
		toSerialize["properties"] = o.Properties
	}
	if true {
		toSerialize["isAccountAdmin"] = o.IsAccountAdmin
	}
	if o.Role != nil {
		toSerialize["role"] = o.Role
	}
	if o.Roles != nil {
		toSerialize["roles"] = o.Roles
	}
	if true {
		toSerialize["invitedBy"] = o.InvitedBy
	}
	if true {
		toSerialize["created"] = o.Created
	}
	return json.Marshal(toSerialize)
}

type NullableInvitationModel struct {
	value *InvitationModel
	isSet bool
}

func (v NullableInvitationModel) Get() *InvitationModel {
	return v.value
}

func (v *NullableInvitationModel) Set(val *InvitationModel) {
	v.value = val
	v.isSet = true
}

func (v NullableInvitationModel) IsSet() bool {
	return v.isSet
}

func (v *NullableInvitationModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvitationModel(val *InvitationModel) *NullableInvitationModel {
	return &NullableInvitationModel{value: val, isSet: true}
}

func (v NullableInvitationModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvitationModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


