/*
 * apaleo Identity API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identityclient

import (
	"encoding/json"
)

// UsersListModel struct for UsersListModel
type UsersListModel struct {
	// A collection of users that have access to the current account
	Users []UserItemModel `json:"users"`
}

// NewUsersListModel instantiates a new UsersListModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersListModel(users []UserItemModel) *UsersListModel {
	this := UsersListModel{}
	this.Users = users
	return &this
}

// NewUsersListModelWithDefaults instantiates a new UsersListModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersListModelWithDefaults() *UsersListModel {
	this := UsersListModel{}
	return &this
}

// GetUsers returns the Users field value
func (o *UsersListModel) GetUsers() []UserItemModel {
	if o == nil {
		var ret []UserItemModel
		return ret
	}

	return o.Users
}

// GetUsersOk returns a tuple with the Users field value
// and a boolean to check if the value has been set.
func (o *UsersListModel) GetUsersOk() (*[]UserItemModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Users, true
}

// SetUsers sets field value
func (o *UsersListModel) SetUsers(v []UserItemModel) {
	o.Users = v
}

func (o UsersListModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["users"] = o.Users
	}
	return json.Marshal(toSerialize)
}

type NullableUsersListModel struct {
	value *UsersListModel
	isSet bool
}

func (v NullableUsersListModel) Get() *UsersListModel {
	return v.value
}

func (v *NullableUsersListModel) Set(val *UsersListModel) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersListModel) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersListModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersListModel(val *UsersListModel) *NullableUsersListModel {
	return &NullableUsersListModel{value: val, isSet: true}
}

func (v NullableUsersListModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersListModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


