/*
 * apaleo Identity API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identityclient

import (
	"encoding/json"
)

// InvitationListModel struct for InvitationListModel
type InvitationListModel struct {
	// All invitations to the current account
	Invitations []InvitationModel `json:"invitations"`
}

// NewInvitationListModel instantiates a new InvitationListModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvitationListModel(invitations []InvitationModel) *InvitationListModel {
	this := InvitationListModel{}
	this.Invitations = invitations
	return &this
}

// NewInvitationListModelWithDefaults instantiates a new InvitationListModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvitationListModelWithDefaults() *InvitationListModel {
	this := InvitationListModel{}
	return &this
}

// GetInvitations returns the Invitations field value
func (o *InvitationListModel) GetInvitations() []InvitationModel {
	if o == nil {
		var ret []InvitationModel
		return ret
	}

	return o.Invitations
}

// GetInvitationsOk returns a tuple with the Invitations field value
// and a boolean to check if the value has been set.
func (o *InvitationListModel) GetInvitationsOk() (*[]InvitationModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Invitations, true
}

// SetInvitations sets field value
func (o *InvitationListModel) SetInvitations(v []InvitationModel) {
	o.Invitations = v
}

func (o InvitationListModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["invitations"] = o.Invitations
	}
	return json.Marshal(toSerialize)
}

type NullableInvitationListModel struct {
	value *InvitationListModel
	isSet bool
}

func (v NullableInvitationListModel) Get() *InvitationListModel {
	return v.value
}

func (v *NullableInvitationListModel) Set(val *InvitationListModel) {
	v.value = val
	v.isSet = true
}

func (v NullableInvitationListModel) IsSet() bool {
	return v.isSet
}

func (v *NullableInvitationListModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvitationListModel(val *InvitationListModel) *NullableInvitationListModel {
	return &NullableInvitationListModel{value: val, isSet: true}
}

func (v NullableInvitationListModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvitationListModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


