/*
 * apaleo Identity API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identityclient

import (
	"encoding/json"
)

// InvitedUserToAccountResponseModel struct for InvitedUserToAccountResponseModel
type InvitedUserToAccountResponseModel struct {
	// Email of invited user
	Email string `json:"email"`
}

// NewInvitedUserToAccountResponseModel instantiates a new InvitedUserToAccountResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvitedUserToAccountResponseModel(email string) *InvitedUserToAccountResponseModel {
	this := InvitedUserToAccountResponseModel{}
	this.Email = email
	return &this
}

// NewInvitedUserToAccountResponseModelWithDefaults instantiates a new InvitedUserToAccountResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvitedUserToAccountResponseModelWithDefaults() *InvitedUserToAccountResponseModel {
	this := InvitedUserToAccountResponseModel{}
	return &this
}

// GetEmail returns the Email field value
func (o *InvitedUserToAccountResponseModel) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *InvitedUserToAccountResponseModel) GetEmailOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *InvitedUserToAccountResponseModel) SetEmail(v string) {
	o.Email = v
}

func (o InvitedUserToAccountResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["email"] = o.Email
	}
	return json.Marshal(toSerialize)
}

type NullableInvitedUserToAccountResponseModel struct {
	value *InvitedUserToAccountResponseModel
	isSet bool
}

func (v NullableInvitedUserToAccountResponseModel) Get() *InvitedUserToAccountResponseModel {
	return v.value
}

func (v *NullableInvitedUserToAccountResponseModel) Set(val *InvitedUserToAccountResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableInvitedUserToAccountResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableInvitedUserToAccountResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvitedUserToAccountResponseModel(val *InvitedUserToAccountResponseModel) *NullableInvitedUserToAccountResponseModel {
	return &NullableInvitedUserToAccountResponseModel{value: val, isSet: true}
}

func (v NullableInvitedUserToAccountResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvitedUserToAccountResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


