/*
 * Integration API
 *
 * The Integration API allows apps to ...
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package integrationclient

import (
	"encoding/json"
)

// UiIntegrationCreatedModel struct for UiIntegrationCreatedModel
type UiIntegrationCreatedModel struct {
	Id string `json:"id"`
}

// NewUiIntegrationCreatedModel instantiates a new UiIntegrationCreatedModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUiIntegrationCreatedModel(id string) *UiIntegrationCreatedModel {
	this := UiIntegrationCreatedModel{}
	this.Id = id
	return &this
}

// NewUiIntegrationCreatedModelWithDefaults instantiates a new UiIntegrationCreatedModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUiIntegrationCreatedModelWithDefaults() *UiIntegrationCreatedModel {
	this := UiIntegrationCreatedModel{}
	return &this
}

// GetId returns the Id field value
func (o *UiIntegrationCreatedModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UiIntegrationCreatedModel) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UiIntegrationCreatedModel) SetId(v string) {
	o.Id = v
}

func (o UiIntegrationCreatedModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableUiIntegrationCreatedModel struct {
	value *UiIntegrationCreatedModel
	isSet bool
}

func (v NullableUiIntegrationCreatedModel) Get() *UiIntegrationCreatedModel {
	return v.value
}

func (v *NullableUiIntegrationCreatedModel) Set(val *UiIntegrationCreatedModel) {
	v.value = val
	v.isSet = true
}

func (v NullableUiIntegrationCreatedModel) IsSet() bool {
	return v.isSet
}

func (v *NullableUiIntegrationCreatedModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUiIntegrationCreatedModel(val *UiIntegrationCreatedModel) *NullableUiIntegrationCreatedModel {
	return &NullableUiIntegrationCreatedModel{value: val, isSet: true}
}

func (v NullableUiIntegrationCreatedModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUiIntegrationCreatedModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


