/*
 * Integration API
 *
 * The Integration API allows apps to ...
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package integrationclient

import (
	"encoding/json"
)

// ReplaceUiIntegrationModel struct for ReplaceUiIntegrationModel
type ReplaceUiIntegrationModel struct {
	// Label to be displayed as the name of your integration.  For example, this is the text that is displayed on your user's apps list.
	Label string `json:"label"`
	// Different translations for the integration label.  You can provide as many translations as you want.  You should only provide the iso code of the language for example 'en' for english and 'de' for German. No need for the country.  If there is not a translation for a specific language, we will display the value of the Label as default.
	LabelTranslations *map[string]string `json:"labelTranslations,omitempty"`
	IconSource *string `json:"iconSource,omitempty"`
	SourceUrl string `json:"sourceUrl"`
	// Public source type means, that the browser can see the URL directly. This is true for instance, if you have Hybrid OAuth flow active.                Private source type means, that the server will request from that source URL a public URL, which is pre-authenticated and forward that to the client.
	SourceType string `json:"sourceType"`
	// List of Ids for the properties for which the integration is configured  If the list is empty then the integration is configured for all properties  Remark: Only applicable to non account level integrations
	PropertyIds *[]string `json:"propertyIds,omitempty"`
	// List of Roles for which the integration is configured to be used  If the list is empty then the integration is configured for all roles
	Roles *[]string `json:"roles,omitempty"`
}

// NewReplaceUiIntegrationModel instantiates a new ReplaceUiIntegrationModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReplaceUiIntegrationModel(label string, sourceUrl string, sourceType string) *ReplaceUiIntegrationModel {
	this := ReplaceUiIntegrationModel{}
	this.Label = label
	this.SourceUrl = sourceUrl
	this.SourceType = sourceType
	return &this
}

// NewReplaceUiIntegrationModelWithDefaults instantiates a new ReplaceUiIntegrationModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReplaceUiIntegrationModelWithDefaults() *ReplaceUiIntegrationModel {
	this := ReplaceUiIntegrationModel{}
	return &this
}

// GetLabel returns the Label field value
func (o *ReplaceUiIntegrationModel) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *ReplaceUiIntegrationModel) GetLabelOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *ReplaceUiIntegrationModel) SetLabel(v string) {
	o.Label = v
}

// GetLabelTranslations returns the LabelTranslations field value if set, zero value otherwise.
func (o *ReplaceUiIntegrationModel) GetLabelTranslations() map[string]string {
	if o == nil || o.LabelTranslations == nil {
		var ret map[string]string
		return ret
	}
	return *o.LabelTranslations
}

// GetLabelTranslationsOk returns a tuple with the LabelTranslations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReplaceUiIntegrationModel) GetLabelTranslationsOk() (*map[string]string, bool) {
	if o == nil || o.LabelTranslations == nil {
		return nil, false
	}
	return o.LabelTranslations, true
}

// HasLabelTranslations returns a boolean if a field has been set.
func (o *ReplaceUiIntegrationModel) HasLabelTranslations() bool {
	if o != nil && o.LabelTranslations != nil {
		return true
	}

	return false
}

// SetLabelTranslations gets a reference to the given map[string]string and assigns it to the LabelTranslations field.
func (o *ReplaceUiIntegrationModel) SetLabelTranslations(v map[string]string) {
	o.LabelTranslations = &v
}

// GetIconSource returns the IconSource field value if set, zero value otherwise.
func (o *ReplaceUiIntegrationModel) GetIconSource() string {
	if o == nil || o.IconSource == nil {
		var ret string
		return ret
	}
	return *o.IconSource
}

// GetIconSourceOk returns a tuple with the IconSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReplaceUiIntegrationModel) GetIconSourceOk() (*string, bool) {
	if o == nil || o.IconSource == nil {
		return nil, false
	}
	return o.IconSource, true
}

// HasIconSource returns a boolean if a field has been set.
func (o *ReplaceUiIntegrationModel) HasIconSource() bool {
	if o != nil && o.IconSource != nil {
		return true
	}

	return false
}

// SetIconSource gets a reference to the given string and assigns it to the IconSource field.
func (o *ReplaceUiIntegrationModel) SetIconSource(v string) {
	o.IconSource = &v
}

// GetSourceUrl returns the SourceUrl field value
func (o *ReplaceUiIntegrationModel) GetSourceUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceUrl
}

// GetSourceUrlOk returns a tuple with the SourceUrl field value
// and a boolean to check if the value has been set.
func (o *ReplaceUiIntegrationModel) GetSourceUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SourceUrl, true
}

// SetSourceUrl sets field value
func (o *ReplaceUiIntegrationModel) SetSourceUrl(v string) {
	o.SourceUrl = v
}

// GetSourceType returns the SourceType field value
func (o *ReplaceUiIntegrationModel) GetSourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceType
}

// GetSourceTypeOk returns a tuple with the SourceType field value
// and a boolean to check if the value has been set.
func (o *ReplaceUiIntegrationModel) GetSourceTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SourceType, true
}

// SetSourceType sets field value
func (o *ReplaceUiIntegrationModel) SetSourceType(v string) {
	o.SourceType = v
}

// GetPropertyIds returns the PropertyIds field value if set, zero value otherwise.
func (o *ReplaceUiIntegrationModel) GetPropertyIds() []string {
	if o == nil || o.PropertyIds == nil {
		var ret []string
		return ret
	}
	return *o.PropertyIds
}

// GetPropertyIdsOk returns a tuple with the PropertyIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReplaceUiIntegrationModel) GetPropertyIdsOk() (*[]string, bool) {
	if o == nil || o.PropertyIds == nil {
		return nil, false
	}
	return o.PropertyIds, true
}

// HasPropertyIds returns a boolean if a field has been set.
func (o *ReplaceUiIntegrationModel) HasPropertyIds() bool {
	if o != nil && o.PropertyIds != nil {
		return true
	}

	return false
}

// SetPropertyIds gets a reference to the given []string and assigns it to the PropertyIds field.
func (o *ReplaceUiIntegrationModel) SetPropertyIds(v []string) {
	o.PropertyIds = &v
}

// GetRoles returns the Roles field value if set, zero value otherwise.
func (o *ReplaceUiIntegrationModel) GetRoles() []string {
	if o == nil || o.Roles == nil {
		var ret []string
		return ret
	}
	return *o.Roles
}

// GetRolesOk returns a tuple with the Roles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReplaceUiIntegrationModel) GetRolesOk() (*[]string, bool) {
	if o == nil || o.Roles == nil {
		return nil, false
	}
	return o.Roles, true
}

// HasRoles returns a boolean if a field has been set.
func (o *ReplaceUiIntegrationModel) HasRoles() bool {
	if o != nil && o.Roles != nil {
		return true
	}

	return false
}

// SetRoles gets a reference to the given []string and assigns it to the Roles field.
func (o *ReplaceUiIntegrationModel) SetRoles(v []string) {
	o.Roles = &v
}

func (o ReplaceUiIntegrationModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["label"] = o.Label
	}
	if o.LabelTranslations != nil {
		toSerialize["labelTranslations"] = o.LabelTranslations
	}
	if o.IconSource != nil {
		toSerialize["iconSource"] = o.IconSource
	}
	if true {
		toSerialize["sourceUrl"] = o.SourceUrl
	}
	if true {
		toSerialize["sourceType"] = o.SourceType
	}
	if o.PropertyIds != nil {
		toSerialize["propertyIds"] = o.PropertyIds
	}
	if o.Roles != nil {
		toSerialize["roles"] = o.Roles
	}
	return json.Marshal(toSerialize)
}

type NullableReplaceUiIntegrationModel struct {
	value *ReplaceUiIntegrationModel
	isSet bool
}

func (v NullableReplaceUiIntegrationModel) Get() *ReplaceUiIntegrationModel {
	return v.value
}

func (v *NullableReplaceUiIntegrationModel) Set(val *ReplaceUiIntegrationModel) {
	v.value = val
	v.isSet = true
}

func (v NullableReplaceUiIntegrationModel) IsSet() bool {
	return v.isSet
}

func (v *NullableReplaceUiIntegrationModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReplaceUiIntegrationModel(val *ReplaceUiIntegrationModel) *NullableReplaceUiIntegrationModel {
	return &NullableReplaceUiIntegrationModel{value: val, isSet: true}
}

func (v NullableReplaceUiIntegrationModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReplaceUiIntegrationModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


