/*
 * Integration API
 *
 * The Integration API allows apps to ...
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package integrationclient

import (
	"encoding/json"
)

// UiIntegrationListModel struct for UiIntegrationListModel
type UiIntegrationListModel struct {
	UiIntegrations []UiIntegrationItemModel `json:"uiIntegrations"`
	Count int64 `json:"count"`
}

// NewUiIntegrationListModel instantiates a new UiIntegrationListModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUiIntegrationListModel(uiIntegrations []UiIntegrationItemModel, count int64) *UiIntegrationListModel {
	this := UiIntegrationListModel{}
	this.UiIntegrations = uiIntegrations
	this.Count = count
	return &this
}

// NewUiIntegrationListModelWithDefaults instantiates a new UiIntegrationListModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUiIntegrationListModelWithDefaults() *UiIntegrationListModel {
	this := UiIntegrationListModel{}
	return &this
}

// GetUiIntegrations returns the UiIntegrations field value
func (o *UiIntegrationListModel) GetUiIntegrations() []UiIntegrationItemModel {
	if o == nil {
		var ret []UiIntegrationItemModel
		return ret
	}

	return o.UiIntegrations
}

// GetUiIntegrationsOk returns a tuple with the UiIntegrations field value
// and a boolean to check if the value has been set.
func (o *UiIntegrationListModel) GetUiIntegrationsOk() (*[]UiIntegrationItemModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UiIntegrations, true
}

// SetUiIntegrations sets field value
func (o *UiIntegrationListModel) SetUiIntegrations(v []UiIntegrationItemModel) {
	o.UiIntegrations = v
}

// GetCount returns the Count field value
func (o *UiIntegrationListModel) GetCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *UiIntegrationListModel) GetCountOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *UiIntegrationListModel) SetCount(v int64) {
	o.Count = v
}

func (o UiIntegrationListModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["uiIntegrations"] = o.UiIntegrations
	}
	if true {
		toSerialize["count"] = o.Count
	}
	return json.Marshal(toSerialize)
}

type NullableUiIntegrationListModel struct {
	value *UiIntegrationListModel
	isSet bool
}

func (v NullableUiIntegrationListModel) Get() *UiIntegrationListModel {
	return v.value
}

func (v *NullableUiIntegrationListModel) Set(val *UiIntegrationListModel) {
	v.value = val
	v.isSet = true
}

func (v NullableUiIntegrationListModel) IsSet() bool {
	return v.isSet
}

func (v *NullableUiIntegrationListModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUiIntegrationListModel(val *UiIntegrationListModel) *NullableUiIntegrationListModel {
	return &NullableUiIntegrationListModel{value: val, isSet: true}
}

func (v NullableUiIntegrationListModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUiIntegrationListModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


