version: "3.1"

services:
  db:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: secretPassword2021
